Feat: Profile and Feed Functionality implemented for mobile
AOSSIE-Org/Monumento pull request #168
Opened 2024-06-29 21:41 UTC by vkprogrammer-001

This PR implements the following functionality and UI:
- Finished the UI for the profile, feed, and new post_screen
- implemented user profile: showing user info, post tab: showing current user posts, and  bookmark tab: (partially done, as bookmark bloc needs to be implemented first)
- Bloc for profile_posts and follow
- Refactor above mentioned blocs to avoid directly using Firestore as a dependency
- implemented showmodelbottomsheet for settings

2024-06-30 18:13 UTC, mdmohsin7 requested changes
There's a logical bug in the feed, when I like a post and comment on one post, those likes and comments reflect on other posts as well. After refreshing it works fine. I too had this issue while working on the feed, but solved after sometime.

Video:
https://www.loom.com/share/2616aa5225b949b6953718d5d929586a?sid=5be05739-9e9f-4a67-b842-d541e015e24d

2024-07-05 04:50 UTC, vkprogrammer-001 commented
@mdmohsin7 i have fixed the like button logic

2024-07-05 13:04 UTC, mdmohsin7 approved these changes

2024-07-06 06:29 UTC, mdmohsin7 approved these changes

2024-07-11 01:18 UTC, jddeep approved these changes

2024-07-11 01:18 UTC, merged