Adding flutter Gen package ✅
AOSSIE-Org/Monumento pull request #186
Opened 2024-12-06 15:42 UTC by kareemabdeen

## Description
Organized assets for seamless access through generated code.

### Motivation:
The integration of `flutter_gen` improves developer productivity and ensures reliable asset management.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)
## How Has This Been Tested?

- Ran `flutter pub run build_runner build` to generate the asset references.
- Verified that the auto-generated code correctly includes all assets.
- Tested asset usage in the app by replacing hardcoded asset paths with the `flutter_gen`-generated references.
- Ensured the app builds and runs without errors on both debug and release modes.

### Steps to Test:
1. Run `flutter pub run build_runner build` to generate the asset references.
2. Replace any asset path usages in the app with `Assets.<asset_path>`.
3. Run the app locally and ensure all assets (images, fonts, etc.) load correctly.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

---

Let me know if you need any further refinements!

2024-12-06 15:55 UTC, kareemabdeen commented
Can you please review this pr @mdmohsin7

2024-12-06 19:39 UTC, kareemabdeen commented
Hi @mdmohsin7,
I have rebased the current branch (feature/manage-assets-using-flutter-gen) with the updated develop branch, which now includes the latest changes from the recently merged PR. The branch is ready for testing and verification. Once all changes have been reviewed and validated, it can be merged.

2024-12-08 11:42 UTC, mdmohsin7 requested changes
Please check the assets heights and widths

2024-12-08 11:42 UTC, mdmohsin7 commented on lib/presentation/authentication/desktop/reset_password_view_desktop.dart
> -              width: 220,
Hi @kareemabdeen, in few places the width and height has been removed for a few assets, can you pls check them?

2024-12-08 11:42 UTC, mdmohsin7 commented on lib/presentation/authentication/mobile/login_view_mobile.dart
> -                  Image.asset(width: 136, height: 105, 'assets/logo_auth.png'),
Here the width has been omitted but the height is there

2024-12-08 12:02 UTC, kareemabdeen commented
All is dn ✅ @mdmohsin7

2024-12-10 16:39 UTC, mdmohsin7 approved these changes
lgtm

2024-12-10 16:40 UTC, merged