Updated documentation with api information
AOSSIE-Org/Monumento pull request #188
Opened 2024-12-09 19:52 UTC by lakshyasarve

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please include screenshots below if applicable.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

2024-12-10 16:43 UTC, mdmohsin7 requested changes

2024-12-10 16:43 UTC, mdmohsin7 commented on README.md
> +cat .env.template > env
Please change `env` to `.env`

2024-12-10 20:13 UTC, lakshyasarve commented
Completed the suggested changes

2024-12-10 20:13 UTC, lakshyasarve commented on README.md
> +cat .env.template > env
Done!

2024-12-11 15:03 UTC, mdmohsin7 approved these changes
lgtm

2024-12-11 15:03 UTC, merged